module.exports = function (api) {
  api.cache(true);
  return {
    plugins: [
      "react-native-reanimated/plugin",
      [
        "module:react-native-dotenv",
        {
          moduleName: "@env",
          path: ".env",
          blacklist: null,
          whitelist: [
            "BASE_URL",
            "SIGN_UP",
            "VERIFY_EMAIL",
            "LOGIN",
            "REQUEST_PASSWORD",
            "VERIFY_TOKEN",
            "UPDATE_PASSWORD",
            "GET_CATEGORIES",
            "SCHEDULE_CONSULTATION",
            "GET_ALL_SERVICES",
            "VIEW_SERVICE",
            "SEND_MESSAGE",
            "GET_SETTINGS",
            "GET_USER_NOTIFICATIONS",
            "ADD_PRODUCT_TO_WISHLIST",
            "GET_USER_WISHLIST",
            "DELETE_USER_WISHLIST",
            "ADD_PRODUCT_TO_RECENTLY_VIEWED",
            "GET_USER_RECENTLY_VIEWED",
            "DELETE_USER_RECENTLY_VIEWED",
            "GET_USER_REFERRAL",
            "GET_USER_REFERRAL_REWARD_HISTORY",
            "GET_ALL_USER_CHATS",
            "GET_USER_SERVICE_MESSAGE",
            "SEND_CHAT_MESSAGE",
            "UPDATE_USER_PROFILE",
            "GET_TERMS_AND_CONDITIONS",
            "GET_USER_PREFERENCES",
            "UPDATE_USER_PROFILE_FORM",
            "SAVE_USER_PREFERENCES",
            "REFRESH_USER_PROFILE",
            "DELETE_USER_ACCOUNT",
          ],
          safe: false,
          allowUndefined: true,
        },
      ],
    ],
    presets: ["babel-preset-expo"],
  };
};
